
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.hostname = "Lab1VM"
  config.vm.synced_folder "../../sync_folder", "/home/vagrant/data"
  config .vm.provision "file", source: "../copied.txt", destination: "/home/vagrant/copied.txt"
  
  config.vm.provider :virtualbox do |vb|
  	vb.customize ["modifyvm", :id, "--memory", 2048]
  end
end
